import { Product } from "@/types/product";

const shopData: Product[] = [
  {
    _id: "1",
    title: "Havit HV-G69 USB Gamepad",
    slug: "havit-hv-g69-usb-gamepad",
    description: "The Havit HV-G69 USB Gamepad delivers precise control with dual analog sticks, responsive D-pad, and ergonomic design. Compatible with PC and PS3, it features vibration feedback for immersive gaming. Plug-and-play USB connectivity with a 1.5m cable for comfortable gameplay.",
    brand: "Havit",
    price: 1499,
    discountedPrice: 899,
    compareAtPrice: 1799,
    images: [
      "https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&h=400&fit=crop",
    ],
    category: "4",
    tags: ["gaming", "controller", "pc", "usb"],
    sku: "HV-G69-BLK",
    stock: 45,
    trackQuantity: true,
    status: "active",
    ratings: { average: 4.2, count: 38 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    specifications: [
      { key: "Connectivity", value: "USB 2.0" },
      { key: "Compatibility", value: "PC, PS3" },
      { key: "Cable Length", value: "1.5m" },
      { key: "Vibration", value: "Dual motor" },
    ],
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },
  {
    _id: "2",
    title: "iPhone 14 Plus, 6/128GB",
    slug: "iphone-14-plus-6-128gb",
    description: "iPhone 14 Plus features a 6.7-inch Super Retina XDR display, A15 Bionic chip with 5-core GPU, and an advanced dual-camera system with 12MP main and ultra wide cameras. All-day battery life, Ceramic Shield front cover, and IP68 water resistance.",
    brand: "Apple",
    price: 79900,
    discountedPrice: 69900,
    compareAtPrice: 89900,
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400&h=400&fit=crop",
    ],
    category: "3",
    tags: ["apple", "iphone", "smartphone", "5g"],
    sku: "APL-IP14P-128-BLK",
    stock: 25,
    trackQuantity: true,
    status: "active",
    ratings: { average: 4.6, count: 124 },
    isActive: true,
    isFeatured: true,
    hasVariants: true,
    variantOptions: [
      { name: "color", values: ["Black", "Blue", "Purple", "Red"] },
      { name: "storage", values: ["128GB", "256GB", "512GB"] },
    ],
    variants: [
      { title: "Black 128GB", sku: "APL-IP14P-128-BLK", price: 69900, stock: 8, option1: "Black", option2: "128GB" },
      { title: "Blue 128GB", sku: "APL-IP14P-128-BLU", price: 69900, stock: 6, option1: "Blue", option2: "128GB" },
      { title: "Black 256GB", sku: "APL-IP14P-256-BLK", price: 79900, stock: 5, option1: "Black", option2: "256GB" },
      { title: "Blue 256GB", sku: "APL-IP14P-256-BLU", price: 79900, stock: 6, option1: "Blue", option2: "256GB" },
    ],
    specifications: [
      { key: "Display", value: "6.7-inch Super Retina XDR" },
      { key: "Chip", value: "A15 Bionic" },
      { key: "Camera", value: "12MP Main + 12MP Ultra Wide" },
      { key: "Battery", value: "Up to 26 hours video playback" },
      { key: "Water Resistance", value: "IP68 (6m for 30 min)" },
    ],
    createdAt: "2024-02-10",
    updatedAt: "2024-02-10",
  },
  {
    _id: "3",
    title: "Apple iMac M1 24-inch 2021",
    slug: "apple-imac-m1-24-inch-2021",
    description: "The 24-inch iMac with M1 chip brings a stunning 4.5K Retina display, 8-core CPU and GPU performance, and a striking thin design in seven vibrant colors. Features a 1080p FaceTime camera, six-speaker sound system, and studio-quality microphones.",
    brand: "Apple",
    price: 129900,
    discountedPrice: 114900,
    compareAtPrice: 139900,
    images: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1484100605678-ad79e03e1c90?w=400&h=400&fit=crop",
    ],
    category: "2",
    tags: ["apple", "imac", "desktop", "all-in-one"],
    sku: "APL-IMAC-M1-24",
    stock: 12,
    trackQuantity: true,
    status: "active",
    ratings: { average: 4.8, count: 56 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    specifications: [
      { key: "Display", value: "24-inch 4.5K Retina" },
      { key: "Chip", value: "Apple M1 (8-core CPU, 8-core GPU)" },
      { key: "Memory", value: "8GB unified memory" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Camera", value: "1080p FaceTime HD" },
    ],
    createdAt: "2024-01-20",
    updatedAt: "2024-01-20",
  },
  {
    _id: "4",
    title: "MacBook Air M1 chip, 8/256GB",
    slug: "macbook-air-m1-chip-8-256gb",
    description: "MacBook Air with M1 chip delivers up to 18 hours of battery life in an ultraportable fanless design. Features a 13.3-inch Retina display with P3 wide color, 8GB unified memory, and 256GB SSD. Backlit Magic Keyboard and Force Touch trackpad.",
    brand: "Apple",
    price: 99900,
    discountedPrice: 84900,
    compareAtPrice: 109900,
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&h=400&fit=crop",
    ],
    category: "2",
    tags: ["apple", "macbook", "laptop", "ultrabook"],
    sku: "APL-MBA-M1-256-SLV",
    stock: 18,
    trackQuantity: true,
    status: "active",
    ratings: { average: 4.7, count: 203 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    specifications: [
      { key: "Display", value: "13.3-inch Retina (2560x1600)" },
      { key: "Chip", value: "Apple M1 (8-core CPU, 8-core GPU)" },
      { key: "Memory", value: "8GB unified memory" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Battery", value: "Up to 18 hours" },
    ],
    createdAt: "2024-01-25",
    updatedAt: "2024-01-25",
  },
  {
    _id: "5",
    title: "Apple Watch Ultra",
    slug: "apple-watch-ultra",
    description: "Apple Watch Ultra features a 49mm titanium case, the brightest Always-On Retina display, and up to 36 hours of battery life. Precision dual-frequency GPS, depth gauge, water temperature sensor, and three specialized bands for adventure.",
    brand: "Apple",
    price: 89900,
    discountedPrice: 79900,
    compareAtPrice: 99900,
    images: [
      "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=400&h=400&fit=crop",
    ],
    category: "7",
    tags: ["apple", "smartwatch", "fitness", "gps"],
    sku: "APL-WU-49-TIT",
    stock: 20,
    trackQuantity: true,
    status: "active",
    ratings: { average: 4.5, count: 87 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    specifications: [
      { key: "Case Size", value: "49mm" },
      { key: "Case Material", value: "Titanium" },
      { key: "Display", value: "Always-On Retina LTPO OLED" },
      { key: "Battery", value: "Up to 36 hours" },
      { key: "Water Resistance", value: "WR100 / EN 13319" },
    ],
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
  },
  {
    _id: "6",
    title: "Logitech MX Master 3 Mouse",
    slug: "logitech-mx-master-3-mouse",
    description: "Logitech MX Master 3 features an electromagnetic scroll wheel with 1000 lines per second, 4000 DPI Darkfield sensor, and ergonomic design sculpted for right-hand comfort. Connects via Bluetooth or Unifying Receiver with 40-day battery life.",
    brand: "Logitech",
    price: 8495,
    discountedPrice: 6995,
    compareAtPrice: 9995,
    images: [
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400&h=400&fit=crop",
    ],
    category: "2",
    tags: ["logitech", "mouse", "wireless", "ergonomic"],
    sku: "LOG-MXM3-GRY",
    stock: 35,
    trackQuantity: true,
    status: "active",
    ratings: { average: 4.8, count: 312 },
    isActive: true,
    isFeatured: false,
    hasVariants: false,
    specifications: [
      { key: "Sensor", value: "Darkfield 4000 DPI" },
      { key: "Connectivity", value: "Bluetooth / Unifying Receiver" },
      { key: "Battery", value: "Up to 40 days" },
      { key: "Scroll Wheel", value: "Electromagnetic MagSpeed" },
    ],
    createdAt: "2024-02-05",
    updatedAt: "2024-02-05",
  },
  {
    _id: "7",
    title: "Apple iPad Air 5th Gen - 64GB",
    slug: "apple-ipad-air-5th-gen-64gb",
    description: "iPad Air 5th generation with M1 chip delivers powerful performance in a thin and light design. Features a 10.9-inch Liquid Retina display, 12MP Wide camera, Touch ID in the top button, and support for Apple Pencil 2 and Magic Keyboard.",
    brand: "Apple",
    price: 54900,
    discountedPrice: 47900,
    compareAtPrice: 59900,
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=400&h=400&fit=crop",
    ],
    category: "3",
    tags: ["apple", "ipad", "tablet", "m1"],
    sku: "APL-IPAD-AIR5-64",
    stock: 22,
    trackQuantity: true,
    status: "active",
    ratings: { average: 4.6, count: 94 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    specifications: [
      { key: "Display", value: "10.9-inch Liquid Retina" },
      { key: "Chip", value: "Apple M1" },
      { key: "Storage", value: "64GB" },
      { key: "Camera", value: "12MP Wide" },
      { key: "Connectivity", value: "Wi-Fi 6, Bluetooth 5.0" },
    ],
    createdAt: "2024-02-12",
    updatedAt: "2024-02-12",
  },
  {
    _id: "8",
    title: "Asus RT-AX58U Dual Band Router",
    slug: "asus-rt-ax58u-dual-band-router",
    description: "ASUS RT-AX58U is a dual-band Wi-Fi 6 router delivering up to 3000 Mbps combined speed. Features AiMesh compatibility, AiProtection Pro lifetime security, adaptive QoS, and VPN client support. MU-MIMO and OFDMA technology for efficient multi-device handling.",
    brand: "Asus",
    price: 12999,
    discountedPrice: 9999,
    compareAtPrice: 14999,
    images: [
      "https://images.unsplash.com/photo-1606904825846-647eb07e5575?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=400&fit=crop",
    ],
    category: "2",
    tags: ["asus", "router", "wifi6", "networking"],
    sku: "ASU-RTAX58U-BLK",
    stock: 30,
    trackQuantity: true,
    status: "active",
    ratings: { average: 4.4, count: 67 },
    isActive: true,
    isFeatured: false,
    hasVariants: false,
    specifications: [
      { key: "Speed", value: "3000 Mbps (574 + 2402)" },
      { key: "Bands", value: "Dual-band 2.4GHz / 5GHz" },
      { key: "Standard", value: "Wi-Fi 6 (802.11ax)" },
      { key: "Ports", value: "4x Gigabit LAN, 1x Gigabit WAN" },
      { key: "Security", value: "AiProtection Pro lifetime" },
    ],
    createdAt: "2024-02-18",
    updatedAt: "2024-02-18",
  },
];

export default shopData;
