import { Product } from "@/types/product";

const shopData: Product[] = [
  {
    _id: "1",
    title: "Havit HV-G69 USB Gamepad",
    slug: "havit-hv-g69-usb-gamepad",
    description: "",
    price: 59.0,
    discountedPrice: 29.0,
    images: [
      "/images/products/product-1-bg-1.png",
      "/images/products/product-1-bg-2.png",
    ],
    category: null,
    tags: [],
    sku: "",
    stock: 10,
    ratings: { average: 4, count: 15 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "2",
    title: "iPhone 14 Plus , 6/128GB",
    slug: "iphone-14-plus-6-128gb",
    description: "",
    price: 899.0,
    discountedPrice: 99.0,
    images: [
      "/images/products/product-2-bg-1.png",
      "/images/products/product-2-bg-2.png",
    ],
    category: null,
    tags: [],
    sku: "",
    stock: 10,
    ratings: { average: 4, count: 5 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "3",
    title: "Apple iMac M1 24-inch 2021",
    slug: "apple-imac-m1-24-inch-2021",
    description: "",
    price: 59.0,
    discountedPrice: 29.0,
    images: [
      "/images/products/product-3-bg-1.png",
      "/images/products/product-3-bg-2.png",
    ],
    category: null,
    tags: [],
    sku: "",
    stock: 10,
    ratings: { average: 4, count: 5 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "4",
    title: "MacBook Air M1 chip, 8/256GB",
    slug: "macbook-air-m1-chip-8-256gb",
    description: "",
    price: 59.0,
    discountedPrice: 29.0,
    images: [
      "/images/products/product-4-bg-1.png",
      "/images/products/product-4-bg-2.png",
    ],
    category: null,
    tags: [],
    sku: "",
    stock: 10,
    ratings: { average: 4, count: 6 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "5",
    title: "Apple Watch Ultra",
    slug: "apple-watch-ultra",
    description: "",
    price: 99.0,
    discountedPrice: 29.0,
    images: [
      "/images/products/product-5-bg-1.png",
      "/images/products/product-5-bg-2.png",
    ],
    category: null,
    tags: [],
    sku: "",
    stock: 10,
    ratings: { average: 4, count: 3 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "6",
    title: "Logitech MX Master 3 Mouse",
    slug: "logitech-mx-master-3-mouse",
    description: "",
    price: 59.0,
    discountedPrice: 29.0,
    images: [
      "/images/products/product-6-bg-1.png",
      "/images/products/product-6-bg-2.png",
    ],
    category: null,
    tags: [],
    sku: "",
    stock: 10,
    ratings: { average: 4, count: 15 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "7",
    title: "Apple iPad Air 5th Gen - 64GB",
    slug: "apple-ipad-air-5th-gen-64gb",
    description: "",
    price: 59.0,
    discountedPrice: 29.0,
    images: [
      "/images/products/product-7-bg-1.png",
      "/images/products/product-7-bg-2.png",
    ],
    category: null,
    tags: [],
    sku: "",
    stock: 10,
    ratings: { average: 4, count: 15 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "8",
    title: "Asus RT Dual Band Router",
    slug: "asus-rt-dual-band-router",
    description: "",
    price: 59.0,
    discountedPrice: 29.0,
    images: [
      "/images/products/product-8-bg-1.png",
      "/images/products/product-8-bg-2.png",
    ],
    category: null,
    tags: [],
    sku: "",
    stock: 10,
    ratings: { average: 4, count: 15 },
    isActive: true,
    isFeatured: true,
    hasVariants: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
];

export default shopData;
