import { BlogItem } from "@/types/blogItem";

const blogData: BlogItem[] = [
  {
    _id: "1",
    title: "How to Start a Successful E-commerce Business",
    slug: "how-to-start-a-successful-e-commerce-business",
    content: "",
    excerpt: "",
    image: "/images/blog/blog-01.jpg",
    category: "General",
    tags: [],
    author: "Admin",
    views: 300000,
    isActive: true,
    publishedAt: "2022-03-27",
    createdAt: "2022-03-27",
  },
  {
    _id: "2",
    title: "The Benefits of Regular Exercise for a Healthy Lifestyle",
    slug: "the-benefits-of-regular-exercise-for-a-healthy-lifestyle",
    content: "",
    excerpt: "",
    image: "/images/blog/blog-02.jpg",
    category: "General",
    tags: [],
    author: "Admin",
    views: 250000,
    isActive: true,
    publishedAt: "2022-03-27",
    createdAt: "2022-03-27",
  },
  {
    _id: "3",
    title: "Exploring the Wonders of Modern Art: A Gallery Tour",
    slug: "exploring-the-wonders-of-modern-art-a-gallery-tour",
    content: "",
    excerpt: "",
    image: "/images/blog/blog-03.jpg",
    category: "General",
    tags: [],
    author: "Admin",
    views: 180000,
    isActive: true,
    publishedAt: "2022-03-27",
    createdAt: "2022-03-27",
  },
  {
    _id: "4",
    title: "The Ultimate Guide to Traveling on a Budget",
    slug: "the-ultimate-guide-to-traveling-on-a-budget",
    content: "",
    excerpt: "",
    image: "/images/blog/blog-04.jpg",
    category: "General",
    tags: [],
    author: "Admin",
    views: 50000,
    isActive: true,
    publishedAt: "2022-03-27",
    createdAt: "2022-03-27",
  },
  {
    _id: "5",
    title: "Cooking Masterclass: Creating Delicious Italian Pasta",
    slug: "cooking-masterclass-creating-delicious-italian-pasta",
    content: "",
    excerpt: "",
    image: "/images/blog/blog-05.jpg",
    category: "General",
    tags: [],
    author: "Admin",
    views: 120000,
    isActive: true,
    publishedAt: "2022-03-27",
    createdAt: "2022-03-27",
  },
  {
    _id: "6",
    title: "Tech Trends 2022: What's Changing in the Digital World",
    slug: "tech-trends-2022-whats-changing-in-the-digital-world",
    content: "",
    excerpt: "",
    image: "/images/blog/blog-06.jpg",
    category: "General",
    tags: [],
    author: "Admin",
    views: 75000,
    isActive: true,
    publishedAt: "2022-03-27",
    createdAt: "2022-03-27",
  },
  {
    _id: "7",
    title: "A Guide to Sustainable Living: Reduce, Reuse, Recycle",
    slug: "a-guide-to-sustainable-living-reduce-reuse-recycle",
    content: "",
    excerpt: "",
    image: "/images/blog/blog-07.jpg",
    category: "General",
    tags: [],
    author: "Admin",
    views: 90000,
    isActive: true,
    publishedAt: "2022-03-27",
    createdAt: "2022-03-27",
  },
  {
    _id: "8",
    title: "The Psychology of Happiness: Finding Joy in Everyday Life",
    slug: "the-psychology-of-happiness-finding-joy-in-everyday-life",
    content: "",
    excerpt: "",
    image: "/images/blog/blog-08.jpg",
    category: "General",
    tags: [],
    author: "Admin",
    views: 150000,
    isActive: true,
    publishedAt: "2022-03-27",
    createdAt: "2022-03-27",
  },
  {
    _id: "9",
    title: "Exploring National Parks: Natural Beauty and Adventure",
    slug: "exploring-national-parks-natural-beauty-and-adventure",
    content: "",
    excerpt: "",
    image: "/images/blog/blog-09.jpg",
    category: "General",
    tags: [],
    author: "Admin",
    views: 60000,
    isActive: true,
    publishedAt: "2022-03-27",
    createdAt: "2022-03-27",
  },
];

export default blogData;
